### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by ryantheleach** [RTLSponge/ore-mockup#1]
Things I know I need to fix: 
- [ ] the "plugin cards" are all slightly too big, having trouble getting the text descriptions to cut off appropriately. 
- [ ] the random / new tabs arn't responsive enough, I need to create a new breakpoint to turn it into yet another dropdown menu. 
- [ ] Text on text based item buttons need hand cursors instead of text select cursors.
